ERROR:root:'data'
ERROR:root:'data'
ERROR:root:'data'
ERROR:root:'data'
ERROR:root:'data'
ERROR:root:HTTPSConnectionPool(host='api.kucoin.com', port=443): Max retries exceeded with url: /api/v1/market/orderbook/level2_20?symbol=AXS-USDT (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002DD9B69ED60>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
